DEF_KEY(√осподин, 0)
DEF_KEY(пришел_в_бар, 1)
DEF_KEY(var, 2)
DEF_KEY(function, 3)
DEF_KEY(if, 4)
DEF_KEY(return, 5)
DEF_KEY(print, 6)
DEF_KEY(scan, 7)
DEF_KEY(sqrt, 8)
DEF_KEY(сколько_уже_можно, 9)

