.TH "main.cpp" 3 "Tue Sep 25 2018" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp \- Main file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'StringArray\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBscan_str_with_delete_and_new\fP (const char *path, int *buf_size, char **buf)"
.br
.RI "Input\&. "
.ti -1c
.RI "bool \fBprint_str\fP (int str_size, char *str)"
.br
.RI "Print string\&. "
.ti -1c
.RI "bool \fBfprint_str\fP (int str_size, char *str, FILE **file)"
.br
.RI "Print string to file\&. "
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main file\&. 


.PP
\fBAuthor:\fP
.RS 4
Yaroslav Pozndyak
.RE
.PP
Main file with main() and description of other global functions\&. 
.SH "Function Documentation"
.PP 
.SS "bool fprint_str (int str_size, char * str, FILE ** file)"

.PP
Print string to file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstr_size\fP size of string 
.br
\fIstr\fP string to printing 
.br
\fIfile\fP pointer to file for printing
.RE
.PP
\fBReturns:\fP
.RS 4
sucsess
.RE
.PP
\fBNote:\fP
.RS 4
print string to file 
.RE
.PP

.SS "bool print_str (int str_size, char * str)"

.PP
Print string\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstr_size\fP size of string 
.br
\fIstr\fP string to printing
.RE
.PP
\fBReturns:\fP
.RS 4
sucsess
.RE
.PP
\fBNote:\fP
.RS 4
print string 
.RE
.PP

.SS "bool scan_str_with_delete_and_new (const char * path, int * buf_size, char ** buf)"

.PP
Input\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP pointer to path to input file 
.br
\fIbuf_size\fP pointer to size of file 
.br
\fIbuf\fP pointer to data
.RE
.PP
\fBReturns:\fP
.RS 4
sucsess
.RE
.PP
\fBNote:\fP
.RS 4
Delete buf and buf_size\&. Scan file to buf\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
