.TH "StringArray.cpp" 3 "Tue Sep 25 2018" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StringArray.cpp \- String Array description\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'StringArray\&.h'\fP
.br

.SH "Detailed Description"
.PP 
String Array description\&. 


.PP
\fBAuthor:\fP
.RS 4
Yaroslav Pozndyak
.RE
.PP
File with a description of the class \fBStringArray\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
