.TH "StringArray.h" 3 "Tue Sep 25 2018" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StringArray.h \- String Array declaration\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'info\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStringArray\fP"
.br
.RI "Main class\&. "
.in -1c
.SH "Detailed Description"
.PP 
String Array declaration\&. 


.PP
\fBAuthor:\fP
.RS 4
Yaroslav Pozndyak
.RE
.PP
File with a declaration of the class \fBStringArray\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
